function Createfigure_pvalues_vs_Sparsity(Y1,FigTitle,pval,Legend_Text)
%CREATEFIGURE(Y1,XDATA1,YDATA1)
%  Y1:  vector of y data
%
%  Auto-generated by MATLAB on 12-Jun-2009 16:01:11
%
%
% Lester Melie Garcia
% Neuroimaging Department
% Cuban Neuroscience Center
% June 12th, 2009. 
% Last update: November 22nd, 2009

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontSize',14);
box('on');
hold('all');

% Create plot
X1 = 50:2:96; X1 = X1./100; X1 = X1(:);
[Nr,Nc] = size(Y1);
X1 = X1(1:Nr);
X1 = repmat(X1,1,Nc);
%Y1 = Y1(:);
NFiles = size(Y1,2);
if NFiles==1
    plot(X1,Y1,'MarkerFaceColor',[0 0 0],'MarkerEdgeColor',[0 0 0],'MarkerSize',8,'Marker','o',...
        'LineStyle','none',...
        'Color',[0 0 0]);
else
    plot(X1(:,1),Y1(:,1),'MarkerFaceColor',[0 0 0],'MarkerEdgeColor',[0 0 0],'MarkerSize',8,'Marker','o',...
        'LineStyle','none',...
        'Color',[0 0 0]);
    hold on;
    plot(X1(:,2),Y1(:,2),'MarkerFaceColor',[0 0 0],'MarkerEdgeColor',[0 0 0],'MarkerSize',8,'Marker','^',...
        'LineStyle','none',...
        'Color',[0 0 0]);
    legend(Legend_Text);
end;
% Create line
XData1 = [min(X1(:,1)) max(X1(:,1))];
YData1 = [pval,pval];
line(XData1,YData1,'Parent',axes1,'LineWidth',3,'LineStyle','--',...
    'Color',[0 0 0]);

% Create xlabel
xlabel({'Sparsity Degree'},'FontWeight','bold','FontSize',14,...
    'FontName','Arial');

% Create ylabel
ylabel({'p-value'},'FontWeight','bold','FontSize',14,'FontName','Arial');

% Create title
title({FigTitle},'FontWeight','bold','FontSize',16,...
    'FontName','Arial');
% title({'AAL versus Jacob'},'FontWeight','bold','FontSize',16,...
%     'FontName','Arial');

